package br.com.keepcred.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "spu_cre_contratocredito")
public class ContratoCredito {

	@Column
	private Long IDCLIENTE;

	@Column
	private Long CODTIPOSITUACAOTITULO;

	@Id
	@Column
	private Long NUMCONTRATOCREDITO;

	@Column
	private Long IDMODALIDADEPRODUTO;

	@Column
	private float VALORSALDODEVEDORCONTABIL;

	public ContratoCredito() {
		super();
	}

	public ContratoCredito(Long iDCLIENTE, Long cODTIPOSITUACAOTITULO, Long nUMCONTRATOCREDITO,
			Long iDMODALIDADEPRODUTO, float vALORSALDODEVEDORCONTABIL) {
		super();
		IDCLIENTE = iDCLIENTE;
		CODTIPOSITUACAOTITULO = cODTIPOSITUACAOTITULO;
		NUMCONTRATOCREDITO = nUMCONTRATOCREDITO;
		IDMODALIDADEPRODUTO = iDMODALIDADEPRODUTO;
		VALORSALDODEVEDORCONTABIL = vALORSALDODEVEDORCONTABIL;
	}

	public Long getIDCLIENTE() {
		return IDCLIENTE;
	}

	public void setIDCLIENTE(Long iDCLIENTE) {
		IDCLIENTE = iDCLIENTE;
	}

	public Long getCODTIPOSITUACAOTITULO() {
		return CODTIPOSITUACAOTITULO;
	}

	public void setCODTIPOSITUACAOTITULO(Long cODTIPOSITUACAOTITULO) {
		CODTIPOSITUACAOTITULO = cODTIPOSITUACAOTITULO;
	}

	public Long getNUMCONTRATOCREDITO() {
		return NUMCONTRATOCREDITO;
	}

	public void setNUMCONTRATOCREDITO(Long nUMCONTRATOCREDITO) {
		NUMCONTRATOCREDITO = nUMCONTRATOCREDITO;
	}

	public Long getIDMODALIDADEPRODUTO() {
		return IDMODALIDADEPRODUTO;
	}

	public void setIDMODALIDADEPRODUTO(Long iDMODALIDADEPRODUTO) {
		IDMODALIDADEPRODUTO = iDMODALIDADEPRODUTO;
	}

	public float getVALORSALDODEVEDORCONTABIL() {
		return VALORSALDODEVEDORCONTABIL;
	}

	public void setVALORSALDODEVEDORCONTABIL(float vALORSALDODEVEDORCONTABIL) {
		VALORSALDODEVEDORCONTABIL = vALORSALDODEVEDORCONTABIL;
	}

	@Override
	public String toString() {
		return "ContratoCredito [IDCLIENTE=" + IDCLIENTE + ", CODTIPOSITUACAOTITULO=" + CODTIPOSITUACAOTITULO
				+ ", NUMCONTRATOCREDITO=" + NUMCONTRATOCREDITO + ", IDMODALIDADEPRODUTO=" + IDMODALIDADEPRODUTO
				+ ", VALORSALDODEVEDORCONTABIL=" + VALORSALDODEVEDORCONTABIL + "]";
	}

}
